name: dailyreport
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch: # 手動でワークフローをトリガーするためのオプション
  
  
jobs:
  my-job:
    runs-on: ubuntu-latest # ジョブが実行される環境を指定
    steps:
      - name: first step
        run: echo "Hello World."